version: '3.3'
services:
  web:
    build: .
    container_name: main_pro
    volumes: 
      - .:/code
    depends_on:
      - redis
      - worker_main
    restart: on-failure
    command: "python codes/p1.py"
  
  worker_main:
    build: .
    container_name: worker_main
    depends_on:
      - redis
    command: rq worker --url redis://redis:6379/0

  redis:
    image: "redis:alpine"
    